import ContentCustomizationForm from '@/components/ui/ContentCustomizationForm'; // Import the form component
import { useState } from 'react'; // React hook to handle state
import { customizeContent } from '@/utils/contentCustomization'; // Import the content customization logic

const Page: React.FC = () => {
    const [generatedContent, setGeneratedContent] = useState(''); // State to store generated content

    // Function to handle customization
    const handleCustomize = (tone: string, style: string, audience: string) => {
        const content = "Sample content generated by AI"; // Placeholder AI-generated content
        const customized = customizeContent(content, tone, style, audience); // Customize the content
        setGeneratedContent(customized); // Set customized content in state
    };

    return (
        <div>
            <h1>AI Content Generator</h1>
            <ContentCustomizationForm onCustomize={handleCustomize} /> {/* Form to capture customization inputs */}
            <div>
                <h2>Generated Content:</h2>
                <p>{generatedContent}</p> {/* Display customized content */}
            </div>
        </div>
    );
};

export default Page;
